-- Baseline migration: reflects the schema as generated by Hibernate ddl-auto=update
-- up to this point. Flyway will NOT execute this against the existing live database
-- (baseline-on-migrate marks it as already applied); it only runs for real if this
-- migration set is ever applied to a brand-new, empty database.

CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    first_name           VARCHAR(255) NOT NULL,
    last_name            VARCHAR(255) NOT NULL,
    email                VARCHAR(255) NOT NULL UNIQUE,
    password             VARCHAR(255) NOT NULL,
    role                 VARCHAR(255) NOT NULL,
    active               BOOLEAN NOT NULL,
    phone                VARCHAR(255),
    profile_picture_url  TEXT
);

CREATE TABLE departments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    name         VARCHAR(255) NOT NULL UNIQUE,
    code         VARCHAR(255) NOT NULL UNIQUE,
    description  VARCHAR(255)
);

CREATE TABLE employees (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    employee_code  VARCHAR(255) NOT NULL UNIQUE,
    first_name     VARCHAR(255) NOT NULL,
    last_name      VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL UNIQUE,
    phone          VARCHAR(255),
    position       VARCHAR(255) NOT NULL,
    salary         NUMERIC(15,2),
    hire_date      DATE,
    status         VARCHAR(255) NOT NULL,
    department_id  BIGINT REFERENCES departments(id),
    user_id        BIGINT UNIQUE REFERENCES users(id)
);

CREATE TABLE attendance_records (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    employee_id  BIGINT NOT NULL REFERENCES employees(id),
    date         DATE NOT NULL,
    check_in     TIME,
    check_out    TIME,
    status       VARCHAR(255) NOT NULL,
    notes        VARCHAR(255),
    user_id      BIGINT REFERENCES users(id),
    CONSTRAINT uq_attendance_records_employee_date UNIQUE (employee_id, date)
);

CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    title         VARCHAR(255) NOT NULL,
    message       TEXT NOT NULL,
    type          VARCHAR(255) NOT NULL,
    is_read       BOOLEAN NOT NULL,
    recipient_id  BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    sender       VARCHAR(255) NOT NULL,
    sender_name  VARCHAR(255) NOT NULL,
    text         TEXT NOT NULL,
    ts           BIGINT NOT NULL,
    type         VARCHAR(255) NOT NULL,
    recipient    VARCHAR(255)
);
